# Generated by Django 4.0.5 on 2022-06-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('CitizenId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('HomeAdress', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('ZipCode', models.PositiveIntegerField()),
                ('LandLine', models.CharField(max_length=12)),
                ('CellularPhone', models.CharField(max_length=12)),
                ('BeenInfected', models.BooleanField(default=False)),
                ('BackGroundDiseases', models.CharField(max_length=100)),
            ],
        ),
    ]
