# Generated by Django 4.0.5 on 2022-06-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VaxFormApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='BeenInfected',
            new_name='BeenInfectedWithCovid',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='BackGroundDiseases',
            field=models.CharField(max_length=200),
        ),
    ]
